spring.application.name=HWICS
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/hwics_dev?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=010709
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.hibernate.ddl-auto=update
spring.jackson.time-zone=Asia/Shanghai

# ???? - ??????
system.statusSaveIntervalMinutes=1

# ??????
system.selfCheckThreshold=0.95

# ???? - ??
system.process.foaming.postWaitMinutes=20
system.process.foaming.cooldownHours=12
system.process.foaming.defaultInjectionRate=10.0
system.process.foaming.defaultInjectionTimeMinutes=60

# ???? - ??
system.process.swabbing.postWaitMinutes=10

# ???? - ??
system.process.gasLift.cooldownHours=24
system.process.gasLift.defaultInjectionRate=15.0
system.process.gasLift.defaultInjectionTimeMinutes=120

# ???? - ????
system.logging.heartbeat.intervalHours=2

# ???? - ????
system.tags.units[0].tag1=1#??????
system.tags.units[1].tag2=2#??????
system.tags.units[2].tag3=3#??????
system.tags.units[3].tag4=4#??????
system.tags.units[4].tag5=5#??????
system.tags.units[5].tag6=6#??????

# ???? - ????
system.tags.production[0].tag1=????
system.tags.production[1].tag2=????
system.tags.production[2].tag3=????
system.tags.production[3].tag4=????

# ??????
logging.level.com.gugusb.hwics=INFO
logging.level.org.springframework=WARN